services:
  beammp-server:
    image: narlyx/beammpd
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    # The enviornment variables below will allow you to include
    #   the following in an enviornemnt file instead of the
    #   ServerConfig.toml that the server provides by default
    #   (Note that these eviornment variables will be copied
    #   to the ServerConfig.toml file after start anyways)
    #environment:
      #- BEAMMP_AUTH_KEY=<your auth key here>
      #- BEAMMP_PORT=30814
      #- BEAMMP_NAME=BeamMP Server
      #- BEAMMP_DESCRIPTION=BeamMP Default Description
      #- BEAMMP_MAP=/levels/gridmap_v2/info.json
      #- BEAMMP_MAX_CARS=1
      #- ENV BEAMMP_MAX_PLAYERS=10
      #- BEAMMP_PRIVATE=true
      #- BEAMMP_DEBUG=false
      #- TZ=UTC
    volumes:
      - ./resources:/data/Resources
      - ./config:/data/Configuration
    ports:
      - 30814:30814/tcp
      - 30814:30814/udp
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
